### ISSUE TITLE
Property mapping error with additional fields

### ISSUE THREAD

**Issue by the-andyman** [nhovratov/jobfair#5]
First of all, thank you for the further development of the extension. 

Unfortunately, I have a problem when sending the application it then appears the following 503 error message:

`ErrorCore: Exception handler (WEB): Uncaught TYPO3 Exception: #1297759968: Exception while property mapping at property path "": Property "firstname" was not found in target object of type "Dan\Jobfair\Domain\Model\Application".`

I had added a field called firstname to the application form.

In the AdditionalConfiguration.php I have set the templateRootPaths and layoutRootPaths as in the documentation.

Im using TYPO3 11.5.12 and jobfair 4.0.2

What can be the reason for the problem?

**Comment by nhovratov** [comment]
Hi, the error appears, because your new field "firstname" does not exist in the Model "Application".
Here is what you need to do:
- Add an additional field to tx_jobfairs_domain_model_application in ext_tables.sql
- Extend the TCA of tx_jobfairs_domain_model_application.php with the new field.
- Lastly, you need to override the Application Model. This is not so easy, as other areas, like the controller, depend on that exact class. I've heard this extension is good: https://extensions.typo3.org/extension/extender but I haven't had tried it yet, so I can't give you tips on that.

**Comment by rhufsky** [comment]
Try to run hov/jobfair 4.0.4 on TPYO3 11.5.22., basically everything is fine, have a sysfolder for the job database, I can create jobs in the backend and they display in the frontend.
When enabling frontend-creation of Jobs, I can add a job, I get a message that the job is added, alas, the job does not show up in the job list and it is not displayed in the frontend. No error message and no other hints.

What can I do?
